### PR TITLE
Crowdbt session

### PR DESCRIPTION
**Pull request by 1heart**

### CODE REVIEW

**Comment by 1heart** [comment]
@ownzandy not fully tested, but a very cursory initialize/judge with a few judges seems to work; also there are no tests and somehow SimpleSession tests are broken (?)

**Comment by 1heart** [comment]
Also needs an updated README referencing https://github.com/anishathalye/gavel/

**Comment by ownzandy** [comment]
wow that looks easier than expected haha
so I can call update_alts whenever I want right?

**Comment by 1heart** [comment]
yep, think so!

**Comment by 1heart** [comment]
It's easy because I'm literally just importing the computation package Anish wrote

**Comment by ownzandy** [comment]
yeah I thought it would involve more than that keeping track of some values and the previous alt

**Comment by ownzandy** [comment]
I get this error 
screen shot 2016-10-09 at 8 07 00 pm
when judges counts is 
screen shot 2016-10-09 at 8 08 05 pm
which seems to be the number of alts

**Comment by ownzandy** [comment]
also I'm not really sure how to test it 
I wrote a script that automatically votes for the participant with the lower id and hoped it would sort the rankings list by participant id which sort of worked (with 2 times the number of alternatives comparisons)

**Comment by ownzandy** [comment]
I also changed the basic auth so it takes env variables so it was easier to deploy on heroku (you can use USER=admin PASSWORD=secret gunicorn hello:app to start it - it's been included in the README)

**Pull request closed without merging**
